# Generated by Django 4.0.5 on 2022-06-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorization',
            name='autorization',
            field=models.CharField(choices=[('None', 'None'), ('Read', 'Read'), ('Write', 'Write')], default='None', max_length=128),
        ),
    ]
