# Generated by Django 4.0.5 on 2022-06-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_autorization_autorization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorization',
            name='myId',
        ),
        migrations.RemoveField(
            model_name='file',
            name='myId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='myId',
        ),
    ]
