# Generated by Django 4.0.5 on 2022-06-08 13:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_autorization_myid_remove_file_myid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autorization',
            new_name='Authorization',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
