# Generated by Django 4.0.5 on 2022-06-10 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
